# Default Configuration:
# https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# Check for Compose options: https://detekt.dev/docs/introduction/compose/

build:
  maxIssues: 0

style:
  MagicNumber:
    # Rule is to sensitive (e.g. you can't define a for loop without using const for from, to and stepSize)
    ignoreRanges: true
    ignoreEnums: true
    ignorePropertyDeclaration: true # Compose
  UnusedPrivateMember:
    active: false
    ignoreAnnotated: [ 'Composable' ]
  WildcardImport:
    active: false
  ReturnCount:
    excludeGuardClauses: true
    max: 3 # Some elvis returns which are not recognized as guard clauses are still readable and clean
    # It is fine to have TO-DO statements
  ForbiddenComment:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated: [ 'Composable', 'Preview' ] # Compose
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Za-z0-9]*' # Compose

complexity:
  LongParameterList:
    active: true
    ignoreAnnotated: [ 'Composable', 'Preview' ] # Compose
  LongMethod:
    active: true
    ignoreAnnotated: [ 'Composable', 'Preview' ] # Compose
  CyclomaticComplexMethod:
    active: true
    ignoreSimpleWhenEntries: true

formatting:
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  NoWildcardImports:
    active: false
  ImportOrdering:
    active: true
    autoCorrect: true
    layout: java.**,javax.**,kotlin.**,kotlinx.**,android,androidx,*,^
