name: Validate Pull Request

on:
  pull_request

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run 'assemble' with Gradle Wrapper
        run: ./gradlew assemble

      - name: Run 'check' with Gradle Wrapper
        run: ./gradlew check

      - name: Upload Detekt Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt
          path: ${{ github.workspace }}/build/reports/detekt
          if-no-files-found: error
          retention-days: 14

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: build/reports/tests/test
          if-no-files-found: error
          retention-days: 14
